// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://powpgjyjpitjdsgofasn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvd3BnanlqcGl0amRzZ29mYXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0Mzc1NzgsImV4cCI6MjA5MTAxMzU3OH0.SE3ClLgXW3h3bkA0_YwPHMc5iyMM6wGwXHTm_4yUZL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});