// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpqvfcmalgvrpoqwbqtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcXZmY21hbGd2cnBvcXdicXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MjE2MDIsImV4cCI6MjA5MTk5NzYwMn0.535f8NcOV3cuMucDHzs1Gbl89-_XdrPnA292ukLNNp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});